import { builtinModules } from "node:module";
import sourcemaps from "rollup-plugin-sourcemaps";
import { defineConfig, type PluginOption } from "vite";

const banner = `/*!
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

const external = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtinModules,
];

const isWatch = process.argv.includes("--watch");

export default defineConfig(({ mode }) => ({
	envPrefix: ["VITE_", "GAUTH_"],
	build: {
		lib: {
			entry: "src/rpgMasterMain.ts",
			formats: ["cjs"],
			fileName: () => "main.js",
			cssFileName: "styles"
		},
		outDir: ".",
		watch: isWatch ? {
			allowInputInsideOutputPath: true,
			exclude: ["**/main.js", "**/*.map"],
		} : undefined,
		emptyOutDir: false,
		sourcemap: mode === "development" ? "inline" : false,
		minify: mode !== "development",
		target: "es2018",
		rollupOptions: {
			external,
			plugins: mode === "development"
				// Only load maps from prebuilt JS dependencies. Let Vite load local sources
				// so Rollup can keep them in the watch graph.
				? [sourcemaps({ include: [".yalc/rpg_shared/dist/**/*.js"] }) as unknown as PluginOption]
				: [],
			output: {
				exports: "named",
				banner,
			},
		},
	},
}));
