import type {
	App,
	TFile,
} from "obsidian";

export type DocumentSyncPolicy = {
	/**
	 * Local document UUID generated by the plugin.
	 */
	docId: string;
	/**
	 * Whether the document sync is enabled.
	 */
	sync: boolean;
};


export function getDocumentSyncPolicy(
	app: App,
	file: TFile,
): DocumentSyncPolicy | null {
	const frontmatter = app.metadataCache.getFileCache(file)?.frontmatter;
	if (!frontmatter?.rpg) {
		return null;
	}

	const { docId, sync } = frontmatter.rpg;

	if (
		typeof docId !== "string" ||
		docId.trim().length === 0 ||
		typeof sync !== "boolean"
	) {
		return null;
	}

	return frontmatter.rpg;
}